### ISSUE TITLE
Remove Composer.lock file

### ISSUE THREAD

**Issue by CJohnson25** [roots/bedrock#450] opened 2019-07-24 15:34 UTC
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing request
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Remove the composer.lock file from the repository

## Motivation

Composer projects should not contain the composer.lock file, as it is an artifact of a build step. Projects using Bedrock as a base, will run into difficulty merging Composer.lock changes between updates. This process can be simplified by ignoring the composer.lock file, and rebuilding based on the merged composer.json file. This goes against the typical composer philosophy, but can aid in automation.

Moving to this structure would require tighter dependency control in order to ensure that projects created from Bedrock have the corret dependencies at any given point in time 

## Additional context

Composer's Recommendation:
https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

Drupal Composer as a comparable project starter kit: 
https://github.com/drupal-composer/drupal-project

Related Issue:
#21

**Comment by swalkinshaw** [comment] 2019-09-27 02:50
I'm closing this because it's a dupe of #21 which has more discussion/details. Since you may have created this one since the other one was locked, I've unlocked it.

However our thinking hasn't changed much on this. There's no clear cut answer and each side has tradeoffs. Even drupal-project has had people asking for the opposite: https://github.com/drupal-composer/drupal-project/issues/492

**Closed by swalkinshaw** 2019-09-27 02:50 UTC
