### ISSUE TITLE
404 On Install

### ISSUE THREAD

**Issue by connormckelvey** [roots/bedrock#159] opened 2015-04-03 13:31 UTC
I installed bedrock using composer and set the root to the "web" directory like the documentation says. However when I go to my dev URL "wordpress.dev", Wordpress redirects me to http://wordpress.dev/wp-admin/install.php which or course doesn't exist by design. So I manually navigate to http://wordpress.dev/wp/wp-admin/install.php, this page is found, but all of the stylesheets and scripts generate 404s. I was actually able to successfully install wordpress but when going to the root again: "wordpress.dev", all of the stylesheets and scripts generate 404s.

**Comment by swalkinshaw** [comment] 2015-04-03 14:26
I'm guessing your `.env` file has some incorrect settings. It should look like:

```ini
WP_HOME=http://wordpress.dev
WP_SITEURL=http://wordpress.dev/wp
```

Closing this as it's more support and not a bug. If you need further help: https://discourse.roots.io/

**Closed by swalkinshaw** 2015-04-03 14:26 UTC

**Comment by connormckelvey** [comment] 2015-04-03 14:28
Nope. That is precisely how my .env file looks.
