### ISSUE TITLE
WP_User Object is null

### ISSUE THREAD

**Issue by o1y** [roots/bedrock#142] opened 2015-02-26 11:49 UTC
When using bedrock it's not possible anymore to get the WP_User object from both themes and plugins. Put the following to your functions.php:
```php
function current_user() {
    var_dump(wp_get_current_user());
}
add_action('init', 'current_user');
```
You'll get an empty WP_User object.
```php
object(WP_User)#118 (7) {
  ["data"]=>
  NULL
  ["ID"]=>
  int(0)
  ["caps"]=>
  array(0) {
  }
  ["cap_key"]=>
  NULL
  ["roles"]=>
  array(0) {
  }
  ["allcaps"]=>
  array(0) {
  }
  ["filter"]=>
  NULL
}
```
Is anyone able to reproduce this issue?

**Comment by Foxaii** [comment] 2015-02-26 12:09
Are you logged in properly?

**Comment by o1y** [comment] 2015-02-26 13:38
Strange. It seems there are zero wp cookies set on my frontend. The LOGGED_IN_COOKIE is missing which is causing the issue. But in the backend all user data are available. Can you replicate this on your frontend side?

**Comment by francescolaffi** [comment] 2015-02-26 14:33
not able to replicate, can you replicate it on a clean install?

you could have some issues with siteurl / homeurl / cookiedomain / cookiepath options/constants, maybe check what cookies get set when you login

**Comment by swalkinshaw** [comment] 2015-03-01 20:17
Can't imagine what in Bedrock would cause this and we can't reproduce it anyway so closing the issue.

**Closed by swalkinshaw** 2015-03-01 20:17 UTC
