### ISSUE TITLE
add_submenu_page not working with johnpbloch/wordpress 4.4.1

### ISSUE THREAD

**Issue by eshimischi** [roots/bedrock#234] opened 2016-02-01 01:15 UTC
Hello. Very strange to say but i made my custom post type Release for Discography and tried to sort out things with add_submenu_page to add an Option submenu with no luck. 

`add_action( 'admin_menu', array( $this, 'add_settings_menu' ) );`

`function add_settings_menu() { add_submenu_page( 'edit.php?post_type=release', 'Options', 'Options', 'edit_plugins', 'label-options', array( $this, 'options_form' ) ); }` 

<img width="478" alt="shot1" src="https://cloud.githubusercontent.com/assets/983201/12706681/cc0ec524-c89a-11e5-9f33-308ef8afda77.png">

This code is working with Official Wordpress and i can see the Option submenu.

Any ideas?

**Comment by QWp6t** [comment] 2016-02-01 03:31
Bedrock does not affect loading admin submenus.

Feel free to ask on https://discourse.roots.io/ or on Stackoverflow or something. 

If you truly believe the issue is with johnpbloch/wordpress (I can assure it's not), then you can also take your issue upstream..

Regardless, this is not an issue to be resolved in the Bedrock codebase so I'm closing this.

**Closed by QWp6t** 2016-02-01 03:31 UTC
